name: Bug
description: Something is broken
title: "[bug] "
labels: ["type: bug"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - api
        - web
        - mobile
        - ml
        - infra
        - db
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
    validations:
      required: true
