@echo off
set REPO=FreshLens-AI/FreshLens-AI

gh issue create --repo %REPO% --title "Finalize and submit project proposal" --label "type: docs" --label "priority: P1" --milestone "M1 - Proposal and planning" --assignee buwaneka-halpage --body-file scripts\issues\01-proposal.md
gh issue create --repo %REPO% --title "Write feasibility study document" --label "type: docs" --label "priority: P1" --milestone "M1 - Proposal and planning" --assignee sathurshna --body-file scripts\issues\02-feasibility.md
gh issue create --repo %REPO% --title "Publish project schedule and Gantt chart" --label "type: docs" --label "priority: P2" --milestone "M1 - Proposal and planning" --assignee buwaneka-halpage --body-file scripts\issues\03-schedule.md
gh issue create --repo %REPO% --title "Write System Requirements Specification (SRS)" --label "type: docs" --label "area: api" --label "priority: P1" --milestone "M2 - SRS and design" --assignee buwaneka-halpage --body-file scripts\issues\04-srs.md
gh issue create --repo %REPO% --title "Write system architecture and design document" --label "type: docs" --label "area: infra" --label "priority: P1" --milestone "M2 - SRS and design" --assignee SMS123456789 --body-file scripts\issues\05-design.md
gh issue create --repo %REPO% --title "Scaffold FastAPI application" --label "type: feature" --label "area: api" --label "priority: P1" --milestone "M3 - Iteration 1 (mid-eval)" --assignee buwaneka-halpage --body-file scripts\issues\06-api-scaffold.md
gh issue create --repo %REPO% --title "Database schema and Row-Level Security policies" --label "type: feature" --label "area: db" --label "priority: P0" --milestone "M3 - Iteration 1 (mid-eval)" --assignee buwaneka-halpage --body-file scripts\issues\07-db-rls.md
gh issue create --repo %REPO% --title "Integrate Supabase Auth and tenant middleware" --label "type: feature" --label "area: api" --label "priority: P1" --milestone "M3 - Iteration 1 (mid-eval)" --assignee buwaneka-halpage --body-file scripts\issues\08-auth.md
gh issue create --repo %REPO% --title "Scaffold Next.js admin dashboard" --label "type: feature" --label "area: web" --label "priority: P1" --milestone "M3 - Iteration 1 (mid-eval)" --assignee SMS123456789 --body-file scripts\issues\09-web-scaffold.md
gh issue create --repo %REPO% --title "Scaffold Expo mobile app with camera screen" --label "type: feature" --label "area: mobile" --label "priority: P1" --milestone "M3 - Iteration 1 (mid-eval)" --assignee sathurshna --body-file scripts\issues\10-mobile-scaffold.md
gh issue create --repo %REPO% --title "Implement POST /scan async endpoint (202 + queue)" --label "type: feature" --label "area: api" --label "priority: P1" --milestone "M3 - Iteration 1 (mid-eval)" --assignee buwaneka-halpage --body-file scripts\issues\11-scan-endpoint.md
gh issue create --repo %REPO% --title "Connect web and mobile clients to API" --label "type: feature" --label "area: api" --label "priority: P1" --milestone "M3 - Iteration 1 (mid-eval)" --assignee SMS123456789 --body-file scripts\issues\12-connect-clients.md
gh issue create --repo %REPO% --title "Expand CI: lint, test, RLS isolation, Docker build" --label "type: chore" --label "area: infra" --label "priority: P1" --milestone "M3 - Iteration 1 (mid-eval)" --assignee buwaneka-halpage --body-file scripts\issues\13-ci.md
gh issue create --repo %REPO% --title "Prepare mid-evaluation demo script" --label "type: docs" --label "priority: P1" --milestone "M3 - Iteration 1 (mid-eval)" --assignee sathurshna --body-file scripts\issues\14-mid-demo.md
gh issue create --repo %REPO% --title "Train CNN for produce classification" --label "type: feature" --label "area: ml" --label "priority: P1" --milestone "M4 - Iteration 2 (ML + integration)" --assignee SMS123456789 --body-file scripts\issues\15-train-cnn.md
gh issue create --repo %REPO% --title "Build Celery ML inference worker" --label "type: feature" --label "area: ml" --label "priority: P1" --milestone "M4 - Iteration 2 (ML + integration)" --assignee buwaneka-halpage --body-file scripts\issues\16-celery-worker.md
gh issue create --repo %REPO% --title "Integrate Cloudflare R2 image storage" --label "type: feature" --label "area: infra" --label "priority: P2" --milestone "M4 - Iteration 2 (ML + integration)" --assignee buwaneka-halpage --body-file scripts\issues\17-r2.md
gh issue create --repo %REPO% --title "Implement low-stock and spoilage alerts" --label "type: feature" --label "area: api" --label "priority: P1" --milestone "M4 - Iteration 2 (ML + integration)" --assignee SMS123456789 --body-file scripts\issues\18-alerts.md
gh issue create --repo %REPO% --title "Build admin analytics dashboard" --label "type: feature" --label "area: web" --label "priority: P1" --milestone "M4 - Iteration 2 (ML + integration)" --assignee SMS123456789 --body-file scripts\issues\19-analytics.md
gh issue create --repo %REPO% --title "System testing and RLS isolation test suite" --label "type: chore" --label "area: db" --label "priority: P1" --milestone "M5 - Testing and final" --assignee buwaneka-halpage --body-file scripts\issues\20-testing.md
gh issue create --repo %REPO% --title "Write testing document" --label "type: docs" --label "priority: P1" --milestone "M5 - Testing and final" --assignee sathurshna --body-file scripts\issues\21-testing-doc.md
gh issue create --repo %REPO% --title "Record and upload demo video" --label "type: docs" --label "priority: P1" --milestone "M5 - Testing and final" --assignee sathurshna --body-file scripts\issues\22-demo-video.md
gh issue create --repo %REPO% --title "Compile final report and submission zip" --label "type: docs" --label "priority: P0" --milestone "M5 - Testing and final" --assignee buwaneka-halpage --body-file scripts\issues\23-final-report.md

echo Done creating issues.
